config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show]
  resources :news_items, only: [:index, :show]
  resources :comments, only: [:index, :create]

  namespace :admin do
    resources :posts
    resources :news_items
  end
  devise_for :admins
  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < Admin::ApplicationController
  def new
    @news_item = NewsItem.new
  end
  def create
    @news_item = NewsItem.new(news_item_params)

    if @news_item.save
    redirect_to [:admin, @news_item]
    else
     render 'new'
    end
  end
  def index
    @news_items = NewsItem.order("news_items").page(params[:page]).per_page(2)
  end
  def show
    @news_item = NewsItem.find(params[:id])
    @comments = @news_item.comments
    @comment = @news_item.comments.new
  end
  def edit
    @news_item = NewsItem.find(params[:id])
  end
  def update
    @news_item = NewsItem.find(params[:id])

    if @news_item.update(news_item_params)
      redirect_to [:admin, @news_item]
    else
      render 'edit'
    end
  end
  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy

    redirect_to [:admin, :news_item]
  end

  private
    def news_item_params
      params.require(:news_item).permit(:title, :content)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)

    if @post.save
    redirect_to [:admin, @post]
    else
     render 'new'
    end
  end
  def index
    @posts = Post.order("posts").page(params[:page]).per_page(2)
  end
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.new
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to [:admin, @post]
    else
      render 'edit'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to [:admin, :posts]
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @comment.commentable }
        format.json { render json: @comment.to_json }
        format.js
      end
    else
     render '_comment_form'
    end
  end

  def index
    @comments = Comment.all

    respond_to do |format|
      format.html
      format.json{ render json: @comments.to_json }
    end
  end
  def comment_params
    params.require(:comment).permit(:author, :content, :commentable_id, :commentable_type)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.limit(5).order(id: :desc)
    @news_items = NewsItem.limit(5).order(id: :desc)
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  def index
    @news_items = NewsItem.order("news_items").page(params[:page]).per_page(2)
  end

  def show
    @news_item = NewsItem.find(params[:id])
    @comments = @news_item.comments
    @comment = @news_item.comments.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("posts").page(params[:page]).per_page(2)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.new
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/news_items_helper.rb
module Admin::NewsItemsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/news_items/edit.html.haml
%h1 Editing news
= form_for [:admin, @news_item] do |f|
  - if @news_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@news_item.errors.count, "error")
        prohibited
        this news from being saved:
      %ul
        - @news_item.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  %p
    = f.label :content
    %br/
    = f.text_area :content, class: "tinymce", rows: "30", cols: "80"
  %p
    = f.submit 'Update news', class: 'btn btn-primary'
= link_to 'Back', news_item_path, class: 'btn btn-primary btn-xs'
= tinymce

app/views/admin/news_items/index.html.haml
%br/
.col-md-3.col-md-offset-6
  =link_to 'Add news', new_admin_news_item_path, class: 'btn btn-primary btn-lg'
%br/
%br/

%p
- @news_items.each do |news_item|
  %h3= link_to news_item.title, admin_news_item_path(news_item.id)
  = truncate_html(news_item.content.html_safe, length: 1000, omission: '...' )
  %br/
  .col-md-2.col-md-offset-10
    =link_to 'Delete', [:admin, news_item], method: :delete, class: 'btn btn-primary'
    =link_to 'Edit', [:edit, :admin, news_item], class: 'btn btn-primary'
  %p
.digg_pagination
  = will_paginate @news_items

app/views/admin/news_items/new.html.haml
= form_for [:admin, @news_item] do |f|
  - if @news_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@news_item.errors.count, "error")
        prohibited
        this news from being saved:
      %ul
        - @news_item.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  %p
    = f.label :content
    %br/
    = f.text_area :content, class: 'tinymce', rows: "30", cols: "80"
  %p
    = f.submit 'Add news', class: 'btn btn-primary'
= link_to 'Back', [:admin, :news_items], class: 'btn btn-primary btn-xs'
= tinymce

app/views/admin/news_items/show.html.haml
%p
  %h2= @news_item.title 
  %br/
  %h4= @news_item.content.html_safe
  %br/
  = link_to 'Back', admin_news_items_path, class: 'btn btn-primary btn-xs'

  .col-md-2.col-md-offset-10
    =link_to 'Delete', [:admin, @news_item], method: :delete, class: 'btn btn-primary'
    =link_to 'Edit', [:edit, :admin, @news_item], class: 'btn btn-primary'
= render 'comments/comment_form'

app/views/admin/posts/edit.html.haml
%h1 Editing post
= form_for [:admin, @post] do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited
        this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  %p
    = f.label :content
    %br/
    = f.text_area :content, class: "tinymce", rows: "30", cols: "80"
  %p
    = f.submit 'Update post', class: 'btn btn-primary'
= link_to 'Back', posts_path, class: 'btn btn-primary btn-xs'
= tinymce

app/views/admin/posts/index.html.haml
%br/
.col-md-3.col-md-offset-6
  =link_to 'Add Post', new_admin_post_path, class: 'btn btn-primary btn-lg'
%br/
%br/
- @posts.each do |post|
  %h3= link_to post.title, admin_post_path(post.id)
  = truncate_html(post.content.html_safe, length: 1000, omission: '...' )
  %br/
  %br/
  .col-md-2.col-md-offset-10
    =link_to 'Delete', [:admin, post], method: :delete, class: 'btn btn-primary'
    =link_to 'Edit', [:edit, :admin, post], class: 'btn btn-primary'
  %br/
  %br/
.digg_pagination
  = will_paginate @posts

app/views/admin/posts/new.html.haml
= form_for :post, url: admin_posts_path do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  %p
    = f.label :content
    %br/
    = f.text_area :content, class: "tinymce", rows: "30", cols: "80"
  %p
    = f.submit 'Create new post', class: 'btn btn-primary'
= link_to 'Back', posts_path, class: 'btn btn-primary btn-xs'
= tinymce

app/views/admin/posts/show.html.haml
%p
  %h2= @post.title 
  %br/
  %h4= @post.content.html_safe 
  %br/
  = link_to 'Back', admin_posts_path, class: 'btn btn-primary btn-xs'
  %br/
  .col-md-2.col-md-offset-10
    =link_to 'Delete', [:admin, @post], method: :delete, class: 'btn btn-primary'
    =link_to 'Edit', [:edit, :admin, @post], class: 'btn btn-primary'
  %p
= render 'comments/comment_form'

app/views/comments/_comment_form.html.haml
#comments
  - @comments.each do |c|
    %strong= c.author
    = c.content
    %br
    %br


= form_for @comment, remote: true do |f|
  = f.hidden_field :commentable_id
  = f.hidden_field :commentable_type
  = f.label :name
  = f.text_area :author, class: "form-control", rows: "1"
  %br
  = f.text_area :content, class: "form-control", rows: "3"
  %br
  %br
  .col-md-2.col-md-offset-10
    = f.submit 'Add comment', class: 'btn btn-success', id: 'add_comment'

app/views/comments/index.html.haml
- @comments.each do |comment|
  = comment.content
  %br

%button.btn#try_xhr Try

app/views/home/index.html.haml
- if admin_signed_in?
  %br
  .col-md-6
    - @posts.each do |post|
      %h3= link_to post.title, admin_post_path(post.id)
      = truncate_html(post.content, length: 300, omission: '...')
      %br
      %br
  .col-md-5.col-md-offset-1
    - @news_items.each do |news_item|
      %h3= link_to news_item.title, admin_news_item_path(news_item.id)
      = truncate_html(news_item.content.html_safe, length: 300, omission: '...')
      %br
      %br
- else
  %br
  .col-md-6
    - @posts.each do |post|
      %h3= link_to post.title, post_path(post.id)
      = truncate_html(post.content, length: 300, omission: '...')
      %br
      %br
  .col-md-5.col-md-offset-1
    - @news_items.each do |news_item|
      %h3= link_to news_item.title, news_item_path(news_item.id)
      = truncate_html(news_item.content.html_safe, length: 300, omission: '...')
      %br
      %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">BLOG</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
                <% if admin_signed_in? %>
                  <li><a href="/admin/news_items">News</a></li>
                  <li><a href="/admin/posts">Posts</a></li>
                <% else %>
                  <li><a href="/news_items">News</a></li>
                  <li><a href="/posts">Posts</a></li>
                <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if admin_signed_in? %>
                <li><a href="/admin/news_items/new">Add news <span class="sr-only">(current)</span></a></li>
                <li><a href="/admin/posts/new">Add post</a></li>
                <li class="active">
                  <%= link_to "Log out", destroy_admin_session_path, method: :delete%>
                </li>
              <% else %>
                <li class="active">
                  <%= link_to "Log in", admin_session_path, method: :post %>
                </li>
              <% end %>

              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <br>
      <br>
      <br>
<%= yield %>
</div>
<!-- <div class="container">
  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <div class="navbar-header">
        Perfectial-2016
      </div>
    </div>
  </nav>
</div> -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/news_items/index.html.haml
- @news_items.each do |news_item|
  %h3= link_to news_item.title, news_item_path(news_item.id)
  = truncate_html(news_item.content.html_safe, length: 1000, omission: '...' )
.digg_pagination
  = will_paginate @news_items

app/views/news_items/show.html.haml
%p
  %h2= @news_item.title 
  %br/
  %h4= @news_item.content.html_safe
  %br/
  = link_to 'Back', news_item_path, class: 'btn btn-primary btn-xs'
= render 'comments/comment_form'

app/views/posts/index.html.haml
- @posts.each do |post|
  %h3= link_to "#{post.title}", post_path(post.id)
  = truncate_html(post.content.html_safe, length: 1000, omission: '...' )
%br/
%br/
.digg_pagination
  = will_paginate @posts

app/views/posts/show.html.haml
%p
  %h2= @post.title 
  %br
  %h4= @post.content.html_safe
  %br
  = link_to 'Back', posts_path, class: 'btn btn-primary btn-xs'
= render 'comments/comment_form'